application: dream-link
version: 0_1
runtime: python27
api_version: 1
threadsafe: true

handlers:

# Static web resource handling
- url: /(submit/?)?
  static_files: static/submit.html
  upload: static/submit.html

- url: /dream(/.*)?
  static_files: static/dream.html
  upload: static/dream.html

- url: /static
  static_dir: static

# Main handler for backend access
- url: /app/.*
  script: app.dreamlink.application

# Catchall, 404
- url: /.*
  static_files: static/404.html
  upload: static/404.html

libraries:
- name: webapp2
  version: latest